version: '3.8'
services:
  spring-boot-app:
    image: spring-boot-app:latest
    container_name: spring-boot-app
    restart: on-failure
    #表示從當前目錄中的dockerfile文件中建立image
    build: .
    #左邊的端口是主機的端口，右邊的端口是容器的端口。可以通過主機的端口8023存取容器的端口8080
    ports:
      - 8023:8080
    #表示在啟動這個Spring Boot應用程式之前，先讓MySQL服務啟動
    depends_on:
      - mysql-server
    environment:
      MYSQL_DATABASE: productwarehousing
      MYSQL_ROOT_PASSWORD: kikihayashi0425
  mysql-server:
    container_name: mysql-server
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: productwarehousing
      MYSQL_ROOT_PASSWORD: kikihayashi0425
    #使用volumes配置將MySQL數據庫中的數據持久化到主機上
    #建立app/resources資料夾並將sqlCommand裡的所有資料放在容器中的/app/resources內
    volumes:
      - ./src/main/resources/sqlCommand:/docker-entrypoint-initdb.d
#      - D:/Program/Docker Volumn/mysql:/var/lib/mysql
